name: ac_oauth2_client
description: An unopinionated RFC-compliant OAuth 2.0 client which doesn't make assumption on anything
version: 0.4.0
repository: https://github.com/anthochamp/dart-oauth2-client

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ac_dart_essentials: ^0.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  ac_lints: ^0.5.0
  build_runner: ^2.3.3
  freezed: ^3.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.9.3
  test: ^1.24.2
