name: oauth2_client
version: 1.0.0
repository: https://github.com/anthochamp/dart-oauth2-client

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  anthochamp_dart_essentials: 
    git: git@github.com:anthochamp/dart-essentials.git
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  anthochamp_lints:
    git: git@github.com:anthochamp/dart-lints.git
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.24.2
